/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Seguridad;

import YOCHUAS.CompraVuelo;
import Mantenimiento.RegistroCliente;
import Mantenimiento.RegistroEmpleado;
import Mantenimiento.RegistroUsuario;
import Mantenimiento.RegistroVuelo;
import SampleClasses.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Joshu
 */
public class VistaUsuario extends javax.swing.JFrame {
    
    RegistroCliente registroClientes = new RegistroCliente();
    RegistroEmpleado registroEmpleados = new RegistroEmpleado();
    RegistroUsuario registroUsuarios = new RegistroUsuario();
    RegistroVuelo registroVuelos = new RegistroVuelo();
    CompraVuelo compraVuelo = new CompraVuelo();
    Usuario usuario;

    /**
     * Creates new form VistaUsuario
     */
    public VistaUsuario() {
        initComponents();
        
    }

    public VistaUsuario(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        label_Bienvenida.setText("Bienvenido/a: " + usuario.getEmpleado().getNom());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_RCliente = new javax.swing.JButton();
        btn_REmpleado = new javax.swing.JButton();
        btn_RUsuario = new javax.swing.JButton();
        btn_CVuelo = new javax.swing.JButton();
        label_Bienvenida = new javax.swing.JLabel();
        btn_RVuelo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_RCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_RCliente.setText("Registrar Cliente");
        btn_RCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RClienteActionPerformed(evt);
            }
        });

        btn_REmpleado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_REmpleado.setText("Registrar Empleado");
        btn_REmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_REmpleadoActionPerformed(evt);
            }
        });

        btn_RUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_RUsuario.setText("Registrar Usuario");
        btn_RUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RUsuarioActionPerformed(evt);
            }
        });

        btn_CVuelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_CVuelo.setText("Comprar Vuelo");
        btn_CVuelo.setToolTipText("");
        btn_CVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CVueloActionPerformed(evt);
            }
        });

        label_Bienvenida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_Bienvenida.setText("Bienvenido/a: ");

        btn_RVuelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_RVuelo.setText("Registrar Vuelo");
        btn_RVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RVueloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(label_Bienvenida))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_RCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_REmpleado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_RVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_RUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btn_CVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label_Bienvenida)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_RCliente)
                    .addComponent(btn_REmpleado))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_RUsuario)
                    .addComponent(btn_RVuelo))
                .addGap(18, 18, 18)
                .addComponent(btn_CVuelo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RClienteActionPerformed
        registroClientes.setVisible(true);
    }//GEN-LAST:event_btn_RClienteActionPerformed

    private void btn_REmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_REmpleadoActionPerformed
        if (usuario.getEmpleado().getDepartamento().equals("Administrativo")) {
            registroEmpleados.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No tiene permisos para acceder a esta opcion.");
        }
    }//GEN-LAST:event_btn_REmpleadoActionPerformed

    private void btn_RUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RUsuarioActionPerformed
        if (usuario.getEmpleado().getDepartamento().equals("Administrativo")) {
            registroUsuarios.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No tiene permisos para acceder a esta opcion.");
        }
    }//GEN-LAST:event_btn_RUsuarioActionPerformed

    private void btn_CVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CVueloActionPerformed
        compraVuelo.setVisible(true);
    }//GEN-LAST:event_btn_CVueloActionPerformed

    private void btn_RVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RVueloActionPerformed
        if (usuario.getEmpleado().getDepartamento().equals("Administrativo")) {
            registroVuelos.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No tiene permisos para acceder a esta opcion.");
        }
    }//GEN-LAST:event_btn_RVueloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CVuelo;
    private javax.swing.JButton btn_RCliente;
    private javax.swing.JButton btn_REmpleado;
    private javax.swing.JButton btn_RUsuario;
    private javax.swing.JButton btn_RVuelo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_Bienvenida;
    // End of variables declaration//GEN-END:variables
}
