/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Grafos.GrafoVuelos;
import SampleClasses.Vuelo;
import javax.swing.JOptionPane;
import Seguridad.Comprobaciones;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.WindowConstants;

/**
 *
 * @author jdvc, jgsm
 */
public class CompraVuelo extends javax.swing.JFrame {
    
    Comprobaciones comprobaciones = new Comprobaciones();
    ArrayList<String> listaVuelosReservados = new ArrayList<String>();
    
    public CompraVuelo() {
        initComponents();
        cargarClientesDesdeArchivo();
        cmbCantidad();
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                confirmarCierreVentana();
            }
        });
    }
    
    private void confirmarCierreVentana() {
        // Aquí puedes mostrar un mensaje de confirmación y realizar acciones adicionales antes de cerrar la ventana
        int opcion = javax.swing.JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas cerrar la ventana?", "Confirmar cierre", javax.swing.JOptionPane.YES_NO_OPTION);
        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            write("VuelosReservados.txt", listaVuelosReservados);
            dispose(); // Cerrar la ventana
        }
    }
    
    public void cmbCantidad() {
        for (int i = 0; i <= 99; i++) {
            String num = String.valueOf(i);
            cmb_Espacios.addItem(num);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_Pasaporte = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_PaisOrigen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_PaisDestino = new javax.swing.JTextField();
        btn_ReservarVuelo = new javax.swing.JButton();
        cmb_Espacios = new javax.swing.JComboBox<>();
        btn_MostrarVuelos1 = new javax.swing.JButton();

        jLabel4.setText("Pais destino:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_Pasaporte.setToolTipText("");
        txt_Pasaporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PasaporteActionPerformed(evt);
            }
        });

        jLabel2.setText("Pais origen:");

        jLabel3.setText("Pais destino:");

        jLabel1.setText("Pasaporte del cliente:");

        txt_PaisOrigen.setToolTipText("");
        txt_PaisOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PaisOrigenActionPerformed(evt);
            }
        });

        jLabel5.setText("# de acompañantes");

        txt_PaisDestino.setToolTipText("");
        txt_PaisDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PaisDestinoActionPerformed(evt);
            }
        });

        btn_ReservarVuelo.setText("Reservar vuelo");
        btn_ReservarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReservarVueloActionPerformed(evt);
            }
        });

        btn_MostrarVuelos1.setText("Mostrar vuelos disponibles");
        btn_MostrarVuelos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MostrarVuelos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Pasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_PaisOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txt_PaisDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(cmb_Espacios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ReservarVuelo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_MostrarVuelos1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Pasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MostrarVuelos1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_PaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ReservarVuelo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_PaisDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_Espacios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_PasaporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PasaporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PasaporteActionPerformed

    private void txt_PaisOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PaisOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PaisOrigenActionPerformed

    private void txt_PaisDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PaisDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PaisDestinoActionPerformed

    private void btn_ReservarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReservarVueloActionPerformed
        Vuelo vuelo = comprobaciones.devolverVueloAeropuertos(txt_PaisDestino.getText(), txt_PaisOrigen.getText());
        if (vuelo.getCapacidad() > Integer.parseInt(String.valueOf(cmb_Espacios.getSelectedItem()))) {
            vuelo.setCapacidad(vuelo.getCapacidad() - Integer.parseInt(String.valueOf(cmb_Espacios.getSelectedItem())));
            listaVuelosReservados.add(txt_Pasaporte.getText() + "|" + txt_PaisOrigen.getText()
                    + "|" + txt_PaisDestino.getText() + "|" + String.valueOf(cmb_Espacios.getSelectedItem()));
            JOptionPane.showMessageDialog(this, "Vuelo reservado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "La cantidad de acompañantes seleccionada excede la capacidad del vuelo.");
        }

    }//GEN-LAST:event_btn_ReservarVueloActionPerformed

    private void btn_MostrarVuelos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MostrarVuelos1ActionPerformed
        GrafoVuelos grafo = new GrafoVuelos();
        if (comprobaciones.existeCliente(this, txt_Pasaporte.getText())) {
            grafo.grafo(txt_PaisOrigen.getText(), txt_PaisDestino.getText(), Integer.parseInt(String.valueOf(cmb_Espacios.getSelectedItem())));
        } else {
            JOptionPane.showMessageDialog(this, "El pasaporte digitado no coincide con ningun cliente registrado en el sistema.\n"
                    + "Favor Digitar un pasaporte valido para proceder con la busqueda de vuelos disponibles.");
            txt_Pasaporte.setText("");
        }
    }//GEN-LAST:event_btn_MostrarVuelos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraVuelo().setVisible(true);
            }
        });
    }
    
    public void write(String txt, ArrayList<String> guardar) {
        String nombreArchivo = txt;
        
        try (PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(nombreArchivo, false)))) {
            for (String s : guardar) {
                out.println(s);
            }
            System.out.println("Los vuelos se han guardado correctamente en el archivo " + nombreArchivo);
        } catch (IOException e) {
            System.err.println("Error al guardar los clientes en el archivo " + nombreArchivo + ": " + e.getMessage());
        }
    }
    
    private void cargarClientesDesdeArchivo() {
        String nombreArchivo = "VuelosReservados.txt";
        
        try (BufferedReader br = new BufferedReader(new FileReader(nombreArchivo))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split("\\|");
                if (partes.length == 4) {
                    String vueloReservado = "";
                    vueloReservado += partes[0] + "|" + partes[1] + "|" + partes[2] + "|" + partes[3];
                    listaVuelosReservados.add(vueloReservado);
                }
            }
            System.out.println("Se han cargado " + listaVuelosReservados.size() + " vuelos desde el archivo " + nombreArchivo);
        } catch (IOException e) {
            System.err.println("Error al cargar los vuelos desde el archivo " + nombreArchivo + ": " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_MostrarVuelos1;
    public javax.swing.JButton btn_ReservarVuelo;
    private javax.swing.JComboBox<String> cmb_Espacios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_PaisDestino;
    public javax.swing.JTextField txt_PaisOrigen;
    public javax.swing.JTextField txt_Pasaporte;
    // End of variables declaration//GEN-END:variables
}
